variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - test
    - package
    - deploy
    - bucket

cache:
    - build
    - test
    - package
    - deploy

cache:
    paths:
        - .m2/repository
        - target

build_job:
    stage: build
    tags:
        - docker
    
    script:
        - echo "Maven compile started"
        - cd "$SERVICE_PATH"
        - "mvn compile"

test_job:
    stage: test
    tags:
        - docker
    
    script:
        - echo "Maven test started"
        - cd "$SERVICE_PATH"
        - "mvn test"
    
    artifacts:
        when: always
        reports:
            junit:
                - $SERVICE_PATH/target/surefire-reports/TEST-*.xml

package_job:
    stage: package
    tags:
        - docker
    
    script:
        - echo "Maven packaging started"
        - cd "$SERVICE_PATH"
        - "mvn package"

deploy_job:
    stage: deploy
    tags:
        - docker
    
    script:
        - echo "Maven deploy started"
        - cd "$SERVICE_PATH"
        - "mvn clean compile assembly:single"

deploy to s3:
    stage: bucket
    image:
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    script:
        - aws --version
